<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="15.0.1" />
    <PackageReference Include="FluentValidation" Version="12.0.0" />
    <PackageReference Include="MediatR" Version="13.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RoleBaseAuth.Domain\RoleBaseAuth.Domain.csproj" />
    <ProjectReference Include="..\RoleBaseAuth.Infrastructure\RoleBaseAuth.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Customers\Queries\" />
    <Folder Include="Validators\Customers\" />
  </ItemGroup>

</Project>
